version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - 5000
    ports:
      - "5000:5000"