version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: flaskuser
      MYSQL_DATABASE: TrafficDb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskuser
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    expose:
      - 3306
    ports:
      - "3306:3306"
